-- Create the payments table
CREATE TABLE IF NOT EXISTS pagos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  id_paciente bigint references pacientes(id) on delete cascade not null,
  monto numeric not null,
  metodo text check (metodo in ('Efectivo', 'Tarjeta', 'Transferencia')) not null,
  concepto text not null
);

-- Enable Row Level Security (RLS)
ALTER TABLE pagos ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Specialist can view all payments
CREATE POLICY "Especialistas pueden ver todos los pagos" 
  ON pagos FOR SELECT 
  USING (auth.email() IN (SELECT email FROM especialistas));

-- Specialist can insert payments
CREATE POLICY "Especialistas pueden registrar pagos" 
  ON pagos FOR INSERT 
  WITH CHECK (auth.email() IN (SELECT email FROM especialistas));

-- Patients can view their own payments
CREATE POLICY "Pacientes pueden ver sus propios pagos" 
  ON pagos FOR SELECT 
  USING (
    auth.email() = (SELECT email FROM pacientes WHERE id = pagos.id_paciente)
  );
